import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '../src/auth/AuthContext';
import { supabase } from '../src/lib/supabase';

type Challenge = { id:string; name:string; description:string; icon:string|null; duration_days:number; points_reward:number; min_points_required?:number|null; badge_reward?:string|null };
type UserChallenge = { id:string; challenge_id:string; progress:number; completed:boolean; last_checkin_date?:string|null };

const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

export default function Challenges(){
 const {user}=useAuth(); const [challenges,setChallenges]=useState<Challenge[]>([]); const [mine,setMine]=useState<UserChallenge[]>([]); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'browse'|'mine'>('browse');
 const load=async()=>{if(!user)return; setLoading(true); const [a,b]=await Promise.all([supabase.from('challenges').select('*').order('duration_days'),supabase.from('user_challenges').select('*').eq('user_id',user.id)]); setChallenges((a.data||[]) as Challenge[]);setMine((b.data||[]) as UserChallenge[]);setLoading(false)};
 useEffect(()=>{load()},[user?.id]);
 const joined=new Set(mine.map(x=>x.challenge_id)); const browse=useMemo(()=>challenges.filter(c=>!joined.has(c.id)),[challenges,mine]); const list=tab==='browse'?browse:challenges.filter(c=>joined.has(c.id));
 const join=async(c:Challenge)=>{if(!user)return; const {error}=await supabase.from('user_challenges').insert({user_id:user.id,challenge_id:c.id,progress:0,completed:false});if(error)Alert.alert('Could not join',error.message);else{Alert.alert('Challenge Joined! 🎯',`You're in ${c.name}. Let's crush it!`);load()}};
 const checkIn=async(c:Challenge,uc:UserChallenge)=>{if(uc.last_checkin_date===todayKey()){Alert.alert('Already checked in ⏳','Come back tomorrow!');return} const next=uc.progress+1; const done=next>=c.duration_days; const {error}=await supabase.from('user_challenges').update({progress:next,completed:done,last_checkin_date:todayKey()}).eq('id',uc.id).eq('user_id',user!.id);if(error)Alert.alert('Check-in failed',error.message);else{Alert.alert(done?'Challenge Complete! 🏆':'Checked In! ✅',done?`You earned ${c.points_reward} points!`:`Day ${next}/${c.duration_days} done. Keep going!`);load()}};
 if(loading)return <View style={styles.loading}><ActivityIndicator size="large"/><Text>Loading challenges...</Text></View>;
 return <ScrollView contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>PUSH YOUR LIMITS</Text><Text style={styles.title}>Challenges 🏆</Text><Text style={styles.subtitle}>Earn rewards and level up your habits.</Text>
 <View style={styles.stats}><Stat label="Joined" value={mine.length}/><Stat label="Done" value={mine.filter(x=>x.completed).length}/><Stat label="Points" value={mine.filter(x=>x.completed).reduce((s,x)=>s+(challenges.find(c=>c.id===x.challenge_id)?.points_reward||0),0)}/></View>
 <View style={styles.tabs}><Pressable onPress={()=>setTab('browse')} style={[styles.tab,tab==='browse'&&styles.activeTab]}><Text style={tab==='browse'?styles.activeText:styles.tabText}>Browse ({browse.length})</Text></Pressable><Pressable onPress={()=>setTab('mine')} style={[styles.tab,tab==='mine'&&styles.activeTab]}><Text style={tab==='mine'?styles.activeText:styles.tabText}>My Challenges ({mine.length})</Text></Pressable></View>
 {list.length===0?<View style={styles.empty}><Text style={styles.emptyIcon}>🏆</Text><Text style={styles.emptyText}>{tab==='browse'?'You joined all available challenges! 🎉':'No challenges joined yet. Browse and join one!'}</Text></View>:list.map(c=>{const uc=mine.find(x=>x.challenge_id===c.id);const pct=uc?Math.min(100,Math.round(uc.progress/c.duration_days*100)):0;const locked=(c.min_points_required||0)>0;return <View key={c.id} style={styles.card}><View style={styles.top}><Text style={styles.icon}>{c.icon||'🎯'}</Text><Text style={styles.duration}>{c.duration_days}d</Text></View><Text style={styles.name}>{c.name}</Text><Text style={styles.desc}>{c.description}</Text><Text style={styles.reward}>⚡ {c.points_reward} pts</Text>{uc?<><View style={styles.progressRow}><Text>Day {uc.progress}/{c.duration_days}</Text><Text>{pct}%</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`}]} /></View>{uc.completed?<Text style={styles.completed}>✓ Completed!</Text>:<Pressable style={styles.outline} onPress={()=>checkIn(c,uc)}><Text style={styles.outlineText}>{uc.last_checkin_date===todayKey()?'Done for Today ✓':'Check In Today'}</Text></Pressable>}</>:<Pressable disabled={locked} style={[styles.join,locked&&styles.locked]} onPress={()=>join(c)}><Text style={[styles.joinText,locked&&styles.lockedText]}>{locked?'🔒 Points required':'Join Challenge'}</Text></Pressable>}</View>})}</ScrollView>;
}
function Stat({label,value}:{label:string;value:number}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({container:{padding:20,paddingTop:58,paddingBottom:50,backgroundColor:'#fff'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:10},back:{fontWeight:'800',fontSize:16},eyebrow:{marginTop:28,fontSize:11,fontWeight:'800',letterSpacing:1.2,opacity:.45},title:{fontSize:30,fontWeight:'800',marginTop:5},subtitle:{marginTop:6,opacity:.6},stats:{flexDirection:'row',gap:10,marginTop:20},stat:{flex:1,padding:14,borderRadius:15,backgroundColor:'#f5f5f6'},statValue:{fontSize:22,fontWeight:'800'},statLabel:{fontSize:11,opacity:.55,marginTop:3},tabs:{flexDirection:'row',marginTop:20,padding:4,borderRadius:12,backgroundColor:'#f1f1f2'},tab:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:9},activeTab:{backgroundColor:'#1a1a2e'},tabText:{fontWeight:'700',fontSize:12},activeText:{color:'#fff',fontWeight:'800',fontSize:12},card:{marginTop:12,padding:17,borderRadius:18,borderWidth:1,borderColor:'#e7e7e7'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},icon:{fontSize:30},duration:{paddingVertical:5,paddingHorizontal:9,borderRadius:9,backgroundColor:'#f3f3f4',fontSize:11,fontWeight:'800'},name:{fontSize:17,fontWeight:'800',marginTop:12},desc:{fontSize:13,lineHeight:19,opacity:.6,marginTop:4},reward:{fontSize:12,fontWeight:'700',marginTop:12,opacity:.65},progressRow:{flexDirection:'row',justifyContent:'space-between',marginTop:14,fontSize:12},track:{height:7,backgroundColor:'#eee',borderRadius:8,overflow:'hidden',marginTop:7},fill:{height:'100%',backgroundColor:'#f97316'},join:{marginTop:14,minHeight:44,borderRadius:11,backgroundColor:'#1a1a2e',alignItems:'center',justifyContent:'center'},joinText:{color:'#fff',fontWeight:'800'},locked:{backgroundColor:'#eee'},lockedText:{color:'#777'},outline:{marginTop:13,minHeight:42,borderRadius:11,borderWidth:1,borderColor:'#ddd',alignItems:'center',justifyContent:'center'},outlineText:{fontWeight:'800'},completed:{marginTop:13,fontWeight:'800',color:'#16a34a'},empty:{marginTop:30,padding:30,alignItems:'center'},emptyIcon:{fontSize:40},emptyText:{marginTop:10,textAlign:'center',opacity:.55}
});
