import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '../src/auth/AuthContext';
import { supabase } from '../src/lib/supabase';

type Group={id:string;name:string;description:string;icon:string;member_count:number};
type Message={id:string;message:string;user_id:string;created_at:string;display_name?:string};

export default function Community(){
 const {user}=useAuth(); const [groups,setGroups]=useState<Group[]>([]); const [memberships,setMemberships]=useState<string[]>([]); const [selected,setSelected]=useState<Group|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(''); const [tab,setTab]=useState<'join'|'joined'>('join'); const [loading,setLoading]=useState(true);
 const load=async()=>{if(!user)return;setLoading(true);const [g,m]=await Promise.all([supabase.from('community_groups').select('*').order('name'),supabase.from('community_memberships').select('group_id').eq('user_id',user.id)]);setGroups((g.data||[]) as Group[]);setMemberships((m.data||[]).map((x:any)=>x.group_id));setLoading(false)};
 useEffect(()=>{load()},[user?.id]);
 useEffect(()=>{if(!selected)return;let cancelled=false;(async()=>{const {data}=await supabase.from('community_messages').select('*').eq('group_id',selected.id).order('created_at',{ascending:true}).limit(100);if(cancelled)return;const ids=[...new Set((data||[]).map((x:any)=>x.user_id))];let profiles:any[]=[];if(ids.length){const r=await supabase.from('profiles').select('user_id,display_name').in('user_id',ids);profiles=r.data||[]}const map=new Map(profiles.map(x=>[x.user_id,x.display_name]));setMessages((data||[]).map((x:any)=>({...x,display_name:map.get(x.user_id)||'User'})))} )();return()=>{cancelled=true}},[selected?.id]);
 const join=async(g:Group)=>{const {error}=await supabase.from('community_memberships').insert({group_id:g.id,user_id:user!.id});if(error)Alert.alert('Could not join',error.message);else{Alert.alert('Joined! 🎉',`Welcome to ${g.name}`);load()}};
 const leave=async(g:Group)=>{const {error}=await supabase.from('community_memberships').delete().eq('group_id',g.id).eq('user_id',user!.id);if(error)Alert.alert('Could not leave',error.message);else load()};
 const send=async()=>{if(!text.trim()||!selected)return;const message=text.trim();setText('');const {error}=await supabase.from('community_messages').insert({group_id:selected.id,user_id:user!.id,message});if(error)Alert.alert('Message failed',error.message);else{const {data}=await supabase.from('community_messages').select('*').eq('group_id',selected.id).order('created_at',{ascending:true}).limit(100);setMessages((data||[]).map((x:any)=>({...x,display_name:x.user_id===user!.id?'You':'User'})))}};
 const joined=useMemo(()=>groups.filter(g=>memberships.includes(g.id)),[groups,memberships]);const available=useMemo(()=>groups.filter(g=>!memberships.includes(g.id)),[groups,memberships]);const list=tab==='join'?available:joined;
 if(loading)return <View style={styles.loading}><ActivityIndicator size="large"/><Text>Loading community...</Text></View>;
 if(selected)return <View style={styles.chat}><Pressable onPress={()=>setSelected(null)}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.chatTitle}>{selected.icon} {selected.name}</Text><ScrollView style={styles.messages} contentContainerStyle={{paddingBottom:20}}>{messages.length===0?<Text style={styles.empty}>No messages yet. Start the conversation! 💬</Text>:messages.map(m=><View key={m.id} style={[styles.message,m.user_id===user?.id&&styles.myMessage]}><Text style={styles.sender}>{m.user_id===user?.id?'You':m.display_name}</Text><Text style={styles.messageText}>{m.message}</Text><Text style={styles.time}>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View>)}</ScrollView><View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Type a message..." style={styles.input}/><Pressable onPress={send} style={styles.send}><Text style={styles.sendText}>➤</Text></Pressable></View></View>;
 return <ScrollView contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>STAY ACCOUNTABLE</Text><Text style={styles.title}>Community 👥</Text><Text style={styles.subtitle}>Join groups and grow together.</Text><View style={styles.stats}><Stat label="Groups" value={groups.length}/><Stat label="Joined" value={joined.length}/><Stat label="Available" value={available.length}/></View><View style={styles.tabs}><Pressable onPress={()=>setTab('join')} style={[styles.tab,tab==='join'&&styles.activeTab]}><Text style={tab==='join'?styles.activeText:styles.tabText}>Join ({available.length})</Text></Pressable><Pressable onPress={()=>setTab('joined')} style={[styles.tab,tab==='joined'&&styles.activeTab]}><Text style={tab==='joined'?styles.activeText:styles.tabText}>Joined ({joined.length})</Text></Pressable></View>{list.length===0?<Text style={styles.empty}>Nothing here yet.</Text>:list.map(g=><View key={g.id} style={styles.card}><View style={styles.groupTop}><Text style={styles.icon}>{g.icon}</Text><View style={{flex:1}}><Text style={styles.name}>{g.name}</Text><Text style={styles.members}>👥 {g.member_count.toLocaleString()} members</Text></View></View><Text style={styles.desc}>{g.description}</Text><View style={styles.actions}><Pressable style={styles.action} onPress={()=>tab==='join'?join(g):leave(g)}><Text style={styles.actionText}>{tab==='join'?'Join':'Leave'}</Text></Pressable>{tab==='joined'&&<Pressable style={styles.chatButton} onPress={()=>setSelected(g)}><Text style={styles.chatButtonText}>💬 Chat</Text></Pressable>}</View></View>)}</ScrollView>
}
function Stat({label,value}:{label:string;value:number}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({container:{padding:20,paddingTop:58,paddingBottom:50,backgroundColor:'#fff'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:10},back:{fontSize:16,fontWeight:'800'},eyebrow:{marginTop:28,fontSize:11,fontWeight:'800',letterSpacing:1.2,opacity:.45},title:{fontSize:30,fontWeight:'800',marginTop:5},subtitle:{marginTop:6,opacity:.6},stats:{flexDirection:'row',gap:10,marginTop:20},stat:{flex:1,padding:14,borderRadius:15,backgroundColor:'#f5f5f6'},statValue:{fontSize:22,fontWeight:'800'},statLabel:{fontSize:11,opacity:.55,marginTop:3},tabs:{flexDirection:'row',marginTop:20,padding:4,borderRadius:12,backgroundColor:'#f1f1f2'},tab:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:9},activeTab:{backgroundColor:'#1a1a2e'},tabText:{fontWeight:'700',fontSize:12},activeText:{color:'#fff',fontWeight:'800',fontSize:12},card:{marginTop:12,padding:17,borderRadius:18,borderWidth:1,borderColor:'#e7e7e7'},groupTop:{flexDirection:'row',alignItems:'center'},icon:{fontSize:30,marginRight:12},name:{fontSize:17,fontWeight:'800'},members:{fontSize:11,opacity:.5,marginTop:3},desc:{fontSize:13,lineHeight:19,opacity:.6,marginTop:12},actions:{flexDirection:'row',gap:8,marginTop:14},action:{paddingHorizontal:20,minHeight:40,borderRadius:10,backgroundColor:'#1a1a2e',alignItems:'center',justifyContent:'center'},actionText:{color:'#fff',fontWeight:'800'},chatButton:{paddingHorizontal:16,minHeight:40,borderRadius:10,borderWidth:1,borderColor:'#ddd',alignItems:'center',justifyContent:'center'},chatButtonText:{fontWeight:'800'},empty:{textAlign:'center',padding:35,opacity:.5},chat:{flex:1,padding:20,paddingTop:58,backgroundColor:'#fff'},chatTitle:{fontSize:23,fontWeight:'800',marginTop:18},messages:{flex:1,marginTop:15},message:{alignSelf:'flex-start',maxWidth:'82%',padding:10,borderRadius:14,backgroundColor:'#f1f1f2',marginBottom:8},myMessage:{alignSelf:'flex-end',backgroundColor:'#1a1a2e'},sender:{fontSize:10,fontWeight:'800',opacity:.55,marginBottom:3},messageText:{fontSize:14},time:{fontSize:9,opacity:.45,marginTop:4},composer:{flexDirection:'row',gap:8,paddingTop:10},input:{flex:1,borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:11},send:{width:46,borderRadius:12,backgroundColor:'#1a1a2e',alignItems:'center',justifyContent:'center'},sendText:{color:'#fff',fontSize:20,fontWeight:'800'}});
